pluginManagement {
    repositories {
        mavenLocal()
        maven { url = uri("${settingsDir}/.gradle-local-maven") }
        maven {
            url = 'https://maven.neoforged.net/releases'
            content {
                includeGroupByRegex 'net\\.neoforged.*'
            }
        }
        maven {
            name = 'Mojang Minecraft Libraries'
            url = 'https://libraries.minecraft.net'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        maven { url = uri("${settingsDir}/.gradle-local-maven") }
        mavenLocal {
            metadataSources {
                gradleMetadata()
                mavenPom()
                artifact()
            }
        }
        mavenCentral()
        maven {
            name = 'Mojang Minecraft Libraries'
            url = 'https://libraries.minecraft.net'
        }
        maven {
            url = 'https://maven.neoforged.net/releases'
            content {
                includeGroupByRegex 'net\\.neoforged.*'
            }
        }
        maven {
            name = 'TerraformersMC'
            url = 'https://maven.terraformersmc.com/'
        }
        maven {
            name = 'Shedaniel'
            url = 'https://maven.shedaniel.me'
        }
        maven {
            name = 'ModMaven'
            url = 'https://modmaven.dev'
        }
        maven { url = 'https://api.modrinth.com/maven' }
    }
}
